declare @WK_CUR nvarchar(3)		--通貨
DECLARE @CUR_CODE_CURSOR CURSOR
SET @CUR_CODE_CURSOR = CURSOR FOR

SELECT [CUR_CODE] FROM [DB_name].[dbo].[CUR] WHERE VALID_FLG = 1

OPEN @CUR_CODE_CURSOR

FETCH NEXT FROM @CUR_CODE_CURSOR
INTO
	 @WK_CUR


-- ↓↓ここから伝票集約テーブルのカーソルのループ↓↓
WHILE @@FETCH_STATUS = 0
BEGIN

	--SELECT @WK_CUR,'test'
	FETCH NEXT FROM @CUR_CODE_CURSOR
	INTO
		 @WK_CUR

END
CLOSE @CUR_CODE_CURSOR
DEALLOCATE @CUR_CODE_CURSOR