BACKUP DATABASE [DB] TO  DISK = N'C:\Microsoft SQL Server\BACKUP\DB.bak' WITH NOFORMAT
, INIT,  NAME = N'-完全 データベース バックアップ', SKIP, NOREWIND, NOUNLOAD,COMPRESSION,  STATS = 10
GO

BACKUP DATABASE [DB] TO  DISK = N'C:\Microsoft SQL Server\BACKUP\DB.bak' WITH NOFORMAT
, INIT,  NAME = N'-完全 データベース バックアップ', SKIP, NOREWIND, NOUNLOAD,COMPRESSION,  STATS = 10
GO

BACKUP DATABASE [DB] TO  DISK = N'C:\Microsoft SQL Server\BACKUP\DB.bak' WITH NOFORMAT
, INIT,  NAME = N'-完全 データベース バックアップ', SKIP, NOREWIND, NOUNLOAD,COMPRESSION,  STATS = 10
GO

BACKUP DATABASE [DB] TO  DISK = N'C:\Microsoft SQL Server\BACKUP\DB.bak' WITH NOFORMAT
, INIT,  NAME = N'-完全 データベース バックアップ', SKIP, NOREWIND, NOUNLOAD,COMPRESSION,  STATS = 10
GO
