RESTORE DATABASE [DB_name] FROM  DISK = N'D:\\20080208\\DB.bak' 
WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10
GO

RESTORE DATABASE [DB_name] FROM  DISK = N'D:\\20080208\\DB.bak' 
WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10
GO

RESTORE DATABASE [DB_name] FROM  DISK = N'D:\\20080208\\DB.bak' 
WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10
GO
