WHILE(0=0)
BEGIN

	BEGIN TRANSACTION
	DELETE TOP(50000) FROM [R_1_1_0_SC].[dbo].[D-TABLE]　　//←TOP(50000)が大事
	WHERE
		[Column] = @YM
	SELECT @ACCEPT_ERROR = @@ERROR ,@DELETE_CNT = @@ROWCOUNT
	COMMIT TRANSACTION
	IF @DELETE_CNT = 0
	BEGIN
		BREAK
	END
END
